#!/usr/bin/env bash

## CONFIGURATION

PREFIX=/usr/local/bin         # Directory in which to install the binary
MANPREFIX=/usr/share/man/man1 # Directory in which to install the manual page

## CODE

XDG_PICTURES_DIR=${XDG_PICTURES_DIR:-$HOME/Pictures}
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

if [[ $1 == "clone" ]]; then
    [[ ! -e $PREFIX/moe ]] && sudo cp ./moe $PREFIX/moe
    [[ ! -e $MANPREFIX/moe ]] && sudo cp ./moe.1.gz $MANPREFIX/moe
    [[ ! -e $XDG_CONFIG_HOME/moe ]] && mkdir $XDG_CONFIG_HOME/moe
    [[ ! -e $XDG_PICTURES_DIR/moe ]] && mkdir $XDG_PICTURES_DIR/moe
fi

if [[ $1 == "update" ]]; then
    sudo cp ./moe $PREFIX/moe
    sudo cp ./moe.1.gz $MANPREFIX/moe
fi
 
